/* Canto Compiler and Runtime Engine
 * 
 * ParsedKeepStatement.java
 *
 * Copyright (c) 2018-2020 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.13 $
 */
public class ParsedKeepStatement extends KeepStatement implements Initializable {

    private boolean hasAs = false;
    private boolean hasAsThis = false;
    private boolean hasDynamicAs = false;
    private boolean hasBy = false;

    public ParsedKeepStatement(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setHasAs(boolean hasAs) {
        this.hasAs = hasAs;
    }

    public void setHasAsThis(boolean hasAsThis) {
        this.hasAsThis = hasAsThis;
    }

    public void setHasDynamicAs(boolean hasDynamicAs) {
        this.hasDynamicAs = hasDynamicAs;
    }

    public void setHasBy(boolean hasBy) {
        this.hasBy = hasBy;
    }

    public void init() {
    	if (children != null && children.length > 0) {
            int len = children.length;
            int numNames = 0;
        	
            if (hasAs) {
                setAsName((NameNode) children[0]);
                numNames++;
            } else if (hasAsThis) {
                setAsName(new NameNode(Name.THIS));
            } else if (hasDynamicAs) {
                setAsNameGenerator(children[0]);
                numNames++;
            } else if (hasBy) {
                setByName((NameNode) children[0]);
            }
            if (numNames < len) {
                Instantiation instance = (Instantiation) getChild(len - 1);
                if (instance.getName() == Name.CONTAINER) {
                    setInContainer(true);
                } else {
                    setTableInstance(instance);
                }
            }
        }
    }
}
