/* Canto Compiler and Runtime Engine
 * 
 * ParsedTableElement.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedTableElement extends TableElement implements Initializable {
    public ParsedTableElement(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        // one child means this is the default entry, which has no key
        if (children.length == 1) {
            setKey(null);
            setElement(children[0]);
        } else {
            if (children[0] instanceof Name) {
                setKey(new PrimitiveValue(((Name) children[0]).getName()));
            } else if (children[0] instanceof Value) {
                setKey((Value) children[0]);
            } else {
                setDynamicKey((ValueGenerator) children[0]);
            }
            setElement(children[1]);
        }
    }

}
