/* Canto Compiler and Runtime Engine
 * 
 * ParsedDim.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedDim extends Dim implements Initializable {
    public ParsedDim(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        if (children != null && children.length > 0) {
            AbstractNode node = children[0];
            if (node instanceof Value) {
                int size = ((Value) node).getInt();
                setSize(size);
            } else {
                log("Unable to set Dim size; dimension is not a value.");
            }
        }
    }

    void setDimType(TYPE dimType) {
        setType(dimType);
    }
}
