/* Canto Compiler and Runtime Engine
 * 
 * ParsedAnonymousArray.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import java.util.*;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.7 $
 */
public class ParsedAnonymousArray extends CollectionDefinition implements Initializable {

    public ParsedAnonymousArray(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int len = (children != null ? children.length : 0);
        ArgumentList contents = null;

        // ArrayDefinition expects the contents to be in an ArgumentList
        if (len > 0) {
            contents = new ArgumentList(children);
        }
        NameNode name = new NameNode(Name.ANONYMOUS);
        Dim dim = new Dim(Dim.TYPE.DEFINITE, len);
        List<Dim> dims = new SingleItemList<Dim>(dim);
        setDims(dims);
        setTable(false);
        init(null, name, contents);
    }
}
