/* Canto Compiler and Runtime Engine
 * 
 * ParsedDefTypeName.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import java.util.*;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedDefTypeName extends NameWithParams implements Initializable {
    public ParsedDefTypeName(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        if (children != null && children.length > 0) {
            ArrayList<ParameterList> list = new ArrayList<ParameterList>(children.length);
            for (int i = 0; i < children.length; i++) {
                list.add((ParameterList) children[i]);
            }
            setParamLists(list);
        }
    }
}
