/* Canto Compiler and Runtime Engine
 * 
 * ParsedCharLiteral.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.1 $
 */
public class ParsedCharLiteral extends PrimitiveValue {
    public ParsedCharLiteral(int id) {
        super("", Character.class);
    }

    public void setValue(String val) {
        // unescape backslashes
        val = val.replace("\\n", "\n");
        val = val.replace("\\r", "\r");
        val = val.replace("\\t", "\t");
        val = val.replace("\\\"", "\"");
        val = val.replace("\\\\", "\\");
        
        setValueAndClass(new Character(val.charAt(0)), Character.TYPE);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String toString() {
        return "'" + getString() + "'";
    }
}
