/* Canto Compiler and Runtime Engine
 * 
 * ParsedConstruction.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedConstruction extends Instantiation implements Initializable {
    public ParsedConstruction(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        setReference(children[0]);
        setTrailingDelimiter(true);
    }
    
    public void setConcurrent() {
        setConcurrent(true);
    }

    public void setAnonymous() {
        setAnonymous(true);
    }
}
