/* Canto Compiler and Runtime Engine
 * 
 * ParsedComplexDefinition.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedComplexDefinition extends ComplexDefinition implements Scoped {

    public ParsedComplexDefinition(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int len = children.length;
        if (len > 0) {
            AbstractNode node = children[0];
            if (node instanceof Type) {
                init((Type) node, (NameNode) children[1], (len > 2 ? children[2] : null));
            } else {
                init(null, (NameNode) node, (len > 1 ? children[1] : null));
            }
        }
    }

    public void setModifiers(int access, int dur) {
        setAccess(access);
        setDurability(dur);
    }
    
    public NameNode getDefName() {
        return getNameNode();
    }

}
