/* Canto Compiler and Runtime Engine
 * 
 * ParsedDefCollectionName.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import java.util.*;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.2 $
 */
public class ParsedDefCollectionName extends NameWithDims implements Initializable {
    public ParsedDefCollectionName(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int len = children.length;
        List<Dim> dims;
        List<ParameterList> paramLists;        
        if (len == 0) {
            dims = new EmptyList<Dim>();
            paramLists = null;

        } else if (len == 1) {
            dims = new SingleItemList<Dim>((Dim) children[0]);
            paramLists = null;

        } else {
            dims = new ArrayList<Dim>(len);
            paramLists = new ArrayList<ParameterList>(1);           
            for (int i = 0; i < len; i++) {
                if (children[i] instanceof ParameterList) {
                    paramLists.add((ParameterList) children[i]);
                } else {
                    dims.add((Dim) children[i]);
                }
            }
        }
        setDims(dims);
        setParamLists(paramLists);
    }
}
