/* Canto Compiler and Runtime Engine
 * 
 * ParsedCantoBlock.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 */
public class ParsedCantoBlock extends CantoBlock {

    public ParsedCantoBlock(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    void setCatch(Block block) {
        if (block != null) {
            setCatchBlock(block);
        }
    }
}
