/* Canto Compiler and Runtime Engine
 * 
 * ParsedFloatingPointLiteral.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedFloatingPointLiteral extends PrimitiveValue {
    public ParsedFloatingPointLiteral(int id) {
        super(null, Double.class);
    }

    public void setValue(String val) {
        char lastChar = val.charAt(val.length() - 1);
        if (lastChar == 'f' || lastChar == 'F') {
            try {
                setValueAndClass(Float.valueOf(val), Float.TYPE);
            } catch (NumberFormatException nfe) {
                setValueAndClass(new Float(Float.NaN), Float.TYPE);
            }
        } else {
            try {
                setValueAndClass(Double.valueOf(val), Double.TYPE);
            } catch (NumberFormatException nfe) {
                setValueAndClass(new Double(Double.NaN), Double.TYPE);
            }
        }
    }


    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
