/* Canto Compiler and Runtime Engine
 * 
 * ParsedArguments.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;


/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.9 $
 */
public class ParsedArguments extends ArgumentList implements Initializable {
    public ParsedArguments(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        init(children);
    }
    
    public void setDynamic() {
        setDynamic(true);
    }

    public void setConcurrent() {
        setConcurrent(true);
    }
    
    public void setArray() {
        setArray(true);
    }
    
    public void setTable() {
        setTable(true);
    }
}
