/* Canto Compiler and Runtime Engine
 * 
 * ParsedWithoutPredicate.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */
public class ParsedWithoutPredicate extends WithPredicate implements Initializable {
    public ParsedWithoutPredicate(int id) {
        super(false);
    }

    public void init() {
        setReference(children[0]);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    void setElementPresent(boolean check) {
        setElementPresenceCheck(check);
    }
}
