/* Canto Compiler and Runtime Engine
 * 
 * ParsedStaticText.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.4 $
 */
public class ParsedStaticText extends StaticText {

    private boolean preserveLeading = false;
    private boolean preserveTrailing = false;

    public ParsedStaticText(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    void setPreserveLeading(boolean preserve) {
        preserveLeading = preserve;
    }

    void setPreserveTrailing(boolean preserve) {
        preserveTrailing = preserve;
    }

    public void setTrimLeadingWhitespace(boolean trim) {
        if (preserveLeading) {
            super.setTrimLeadingWhitespace(false);
        } else {
            super.setTrimLeadingWhitespace(trim);
        }
    }

    public void setTrimTrailingWhitespace(boolean trim) {
        if (preserveTrailing) {
            super.setTrimTrailingWhitespace(false);
        } else {
            super.setTrimTrailingWhitespace(trim);
        }
    }
}
