/* Canto Compiler and Runtime Engine
 * 
 * ParsedForExpression.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */
public class ParsedForExpression extends ForStatement implements Initializable {

    public ParsedForExpression(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        int ix = 0;
        while (getChild(ix) instanceof IteratorValues) {
            addIteratorValues((IteratorValues) getChild(ix));
            ix++;
        }
        Block block = (Block) getChild(ix);
        setBody(block);
    }

}
