/* Canto Compiler and Runtime Engine
 * 
 * ParsedWithPredicate.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.6 $
 */
public class ParsedWithPredicate extends WithPredicate implements Initializable {
   
    public ParsedWithPredicate(int id) {
        super(true);
    }

    public void init() {
        setReference(children[0]);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    void setElementPresent(boolean check) {
        setElementPresenceCheck(check);
    }
}
