/* Canto Compiler and Runtime Engine
 * 
 * ParsedTypeList.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import java.util.*;

import canto.lang.*;


/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.3 $
 */
public class ParsedTypeList extends TypeList implements Initializable {
    public ParsedTypeList(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        ArrayList list = new ArrayList(Arrays.asList(children));
        setList(list);
    }
}
