/* Canto Compiler and Runtime Engine
 * 
 * ParsedParameterList.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import java.util.*;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.5 $
 */
public class ParsedParameterList extends ParameterList implements Initializable {
    public ParsedParameterList(int id) {
        super();
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void init() {
        if (children != null) {
            ArrayList<DefParameter> list = new ArrayList<DefParameter>(children.length);
            for (int i = 0; i < children.length; i++) {
                list.add((DefParameter) children[i]);
            }
            setList(list);
        } else {
            setList(new EmptyList<DefParameter>());
        }
    }
    
    public void setDynamic() {
        this.setDynamic(true);
    }
}
