/* Canto Compiler and Runtime Engine
 * 
 * ParsedStringLiteral.java
 *
 * Copyright (c) 2018 by cantolang.org
 * All rights reserved.
 */

package canto.parser;

import canto.lang.*;

/**
 * Based on code generated by jjtree.
 *
 * @author Michael St. Hippolyte
 * @version $Revision: 1.7 $
 */
public class ParsedStringLiteral extends PrimitiveValue {
    public ParsedStringLiteral(int id) {
        super("", String.class);
    }

    public void setValue(String val, boolean singleQuote) {
        // unescape backslashes
        val = val.replace("\\n", "\n");
        val = val.replace("\\r", "\r");
        val = val.replace("\\t", "\t");
        val = val.replace("\\\"", "\"");
        val = val.replace("\\\\", "\\");
        
        // single-quote strings of length 1 become chars
        if (singleQuote && val.length() == 1) {
            setValueAndClass(new Character(val.charAt(0)), Character.TYPE);
        } else {
            setValueAndClass(val, String.class);
        }
    }

    /** Accept the visitor. **/
    public Object jjtAccept(CantoParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String toString() {
        return '"' + getString() + '"';
    }
}
