/* Canto Test Suite: ErrorTest.java
 *
 * Copyright (c) 2018 by cantolang.org
 */

package org.cantolang.test;

import canto.lang.Redirection;


/** ErrorTest is a test class that throws various exceptions,
 *  errors and redirections.
 *
 */
public class ErrorTest {

    public static void throwNullPointerException() {
        throw new NullPointerException("generated by call to ErrorTest.throwNullPointerException");
    }
    
    public static void throwClassNotFoundException() throws ClassNotFoundException {
        throw new ClassNotFoundException("generated by call to ErrorTest.throwClassNotFoundException");
    }
    
    public static void throwNoSuchMethodException() throws NoSuchMethodException {
        throw new NoSuchMethodException("generated by call to ErrorTest.throwNoSuchMethodException");
    }
    
    public static void throwNumberFormatException() {
        throw new NumberFormatException("generated by call to ErrorTest.throwNumberFormatException");
    }
    
    public static void throwIllegalArgumentException() {
        throw new IllegalArgumentException("generated by call to ErrorTest.throwIllegalArgumentException");
    }
    
    public static void throwNoClassDefFoundError() {
        throw new NoClassDefFoundError("generated by call to ErrorTest.throwNoClassDefFoundError");
    }

    public static void throwRedirection() throws Redirection {
        throw new Redirection(Redirection.STANDARD_ERROR, "generated by call to ErrorTest.throwRedirection");
    }
    
    public static void throw404Redirection() throws Redirection {
        throw new Redirection(404, Redirection.STANDARD_ERROR, "generated by call to ErrorTest.throw404Redirection");
    }
}
